---
- name: Check if secret already exists
  shell: oc get secret -n {{ ar_os_registry_secret_namespace }} -o jsonpath='{.items[*].metadata.name}'
  register: secret_stat
  changed_when: false
  failed_when: false

- name: Set Fact Docker Password - from password
  set_fact:
    _ar_os_registry_secret_docker_password: "{{ ar_os_registry_secret_item.password }}"
  when: ar_os_registry_secret_item.password is defined and ar_os_registry_secret_item.password != ''

- name: Set Fact Docker Password - from token
  set_fact:
    _ar_os_registry_secret_docker_password: "{{ ar_os_registry_secret_item.token }}"
  when: ar_os_registry_secret_item.token is defined and ar_os_registry_secret_item.token != ''

- name: Set Fact Service Account default
  set_fact:
    _ar_os_registry_secret_serivce_account: 'default'
  when: ar_os_registry_secret_item.operation is not defined or ar_os_registry_secret_item.operation != 'push'

- name: Set Fact Service Account builder
  set_fact:
    _ar_os_registry_secret_serivce_account: 'builder'
  when: ar_os_registry_secret_item.operation is defined and ar_os_registry_secret_item.operation == 'push'

- name: Create the secret
  command: oc create secret docker-registry {{ ar_os_registry_secret_item.secret_name }} \
    -n {{ ar_os_registry_secret_namespace }}
    --docker-server={{ ar_os_registry_secret_item.server }} \
    --docker-username={{ ar_os_registry_secret_item.username }} \
    --docker-password={{ _ar_os_registry_secret_docker_password }} \
    --docker-email={{ ar_os_registry_secret_item.email | default('') }}
  when: ar_os_registry_secret_item.secret_name not in secret_stat.stdout_lines[0].split(' ')

- name: Associate secret as {{ ar_os_registry_secret_item.operation | default('pull') }} secret for {{ _ar_os_registry_secret_serivce_account }} user in {{ ar_os_registry_secret_item.namespace }}
  include_role:
    name: ar_os_secret_link
    tasks_from: link_secret
  vars:
    ar_os_secret_link_namespace: "{{ ar_os_registry_secret_namespace }}"
    ar_os_secret_link_item: { sa_name: "{{ _ar_os_registry_secret_serivce_account }}",
                              link_secrets: [{ secret_name: "{{ ar_os_registry_secret_item.secret_name }}", operation: "{{ ar_os_registry_secret_item.operation | default('pull') }}" }], }
